import matplotlib.pyplot as p
import mysql.connector as m
mc = m.connect(host  = '127.0.0.1', user = 'root', password='amaatra',database='les')
cur = mc.cursor()
def create():
    cur.execute("create table IT(company varchar(50), wage int(50), employee int(50), stock int(50))")
    mc.commit()
    cur.execute("insert into IT values('Google',140744,139995,108)")
    mc.commit()
    cur.execute("insert into IT values('Microsoft',120662,221000,256)")
    mc.commit()
    cur.execute("insert into IT values('Apple',162650,147000,156)")
    mc.commit()
    cur.execute("insert into IT values('Oracle',132000,143000,75)")
    mc.commit()
    cur.execute("insert into IT values('Accenture',132944,300000,284)")
    mc.commit()
    cur.execute("insert into IT values('Hewlett-Packard',136080,51000,27)")
    mc.commit()
    cur.execute("insert into IT values('Meta',149718,71970,160)")
    mc.commit()
    cur.execute("insert into IT values('TCS',102000,556986,40)")
    mc.commit()
    cur.execute("insert into IT values('Capgemini',94000,340700,170)")
    mc.commit()
    cur.execute("insert into IT values('Infosys',115172,276319,22)")
    mc.commit()
    cur.execute("create table MEDICAL(company varchar(50), wage int(50), employee int(50), stock int(50))")
    mc.commit()
    cur.execute("insert into MEDICAL values('Pfizer',93565,79000,46)")
    mc.commit()
    cur.execute("insert into MEDICAL values('Roche',143000,100920,326)")
    mc.commit()
    cur.execute("insert into MEDICAL values('Abbvie',109435,50000,137)")
    mc.commit()
    cur.execute("insert into MEDICAL values('Johnson & Johnson',130682,142000,163)")
    mc.commit()
    cur.execute("insert into MEDICAL values('Novartis',111333,108514,81)")
    mc.commit()
    cur.execute("insert into MEDICAL values('Bayer',141000,99538,52)")
    mc.commit()
    cur.execute("insert into MEDICAL values('Merck',144007,69000,87)")
    mc.commit()
    cur.execute("insert into MEDICAL values('Bristol Myers Squibb',103718,32200,69)")
    mc.commit()
    cur.execute("insert into MEDICAL values('GlaxoSmithKline',111057,94000,11)")
    mc.commit()
    cur.execute("insert into MEDICAL values('Sanofi',107854,100000,77)")
    mc.commit()
    cur.execute("create table SPORTING(company varchar(50), wage int(50), employee int(50), stock int(50))")
    mc.commit()
    cur.execute("insert into SPORTING values('Nike',99325,79100,106)")
    mc.commit()
    cur.execute("insert into SPORTING values('Academy Sports',98724,170000,43)")
    mc.commit()
    cur.execute("insert into SPORTING values('Bass Pro Shops',108864,40000,35)")
    mc.commit()
    cur.execute("insert into SPORTING values('Adidas',92453,57016,145)")
    mc.commit()
    cur.execute("insert into SPORTING values('Recreational Equipments',96608,256000,17)")
    mc.commit()
    cur.execute("insert into SPORTING values('Big 5 Sporting Goods',84061,95000,17)")
    mc.commit()
    cur.execute("insert into SPORTING values('Modells Sport Goods',104618,5000,23)")
    mc.commit()
    cur.execute("insert into SPORTING values('Puma',116074,16124,61)")
    mc.commit()
    cur.execute("insert into SPORTING values('Reebok',95234,14530,52)")
    mc.commit()
    cur.execute("insert into SPORTING values('Decathlon',120451,93710,60)")
    mc.commit()
    cur.execute("create table AUTOMOBILES(company varchar(50), wage int(50), employee int(50), stock int(50))")
    mc.commit()
    cur.execute("insert into AUTOMOBILES values('Toyota',85320,366283,15)")
    mc.commit()
    cur.execute("insert into AUTOMOBILES values('Volkswagen',99780,662575,150)")
    mc.commit()
    cur.execute("insert into AUTOMOBILES values('Daimler',82127,172000,15)")
    mc.commit()
    cur.execute("insert into AUTOMOBILES values('Ford Motor',92749,186000,16)")
    mc.commit()
    cur.execute("insert into AUTOMOBILES values('Honda',81244,219722,26)")
    mc.commit()
    cur.execute("insert into AUTOMOBILES values('Tesla',131255,1254737,300)")
    mc.commit()
    cur.execute("insert into AUTOMOBILES values('General Motors',86108,157000,42)")
    mc.commit()
    cur.execute("insert into AUTOMOBILES values('Fiat',89000,189545,16)")
    mc.commit()
    cur.execute("insert into AUTOMOBILES values('Hyundai',86000,104731,52)")
    mc.commit()
    cur.execute("insert into AUTOMOBILES values('Nissan',83523,1316134,5)")
    mc.commit()
    cur.execute("create table APPAREL(company varchar(50), wage int(50), employee int(50), stock int(50))")
    mc.commit()
    cur.execute("insert into APPAREL values('Raymond',112326,70900,13)")
    mc.commit()
    cur.execute("insert into APPAREL values('Allen Solly',89749,50000,31)")
    mc.commit()
    cur.execute("insert into APPAREL values('Pantaloons',71800,13300,40)")
    mc.commit()
    cur.execute("insert into APPAREL values('Alexaendaer McQueen',128687,10340,327)")
    mc.commit()
    cur.execute("insert into APPAREL values('Armani',68472,7309,78)")
    mc.commit()
    cur.execute("insert into APPAREL values('ASM Clothing',71800,3750,290)")
    mc.commit()
    cur.execute("insert into APPAREL values('Gucci',130000,17157,530)")
    mc.commit()
    cur.execute("insert into APPAREL values('Prada',110363,12140,52)")
    mc.commit()
    cur.execute("insert into APPAREL values('Hermes',86403,17595,1309)")
    mc.commit()
    cur.execute("insert into APPAREL values('Burberry',138000,9324,20)")
    mc.commit()
    cur.execute("create table BANKING(company varchar(50), wage int(50), employee int(50), stock int(50))")
    mc.commit()
    cur.execute("insert into BANKING values('JP Morgan',94000,250355,119)")
    mc.commit()
    cur.execute("insert into BANKING values('Japan Post Holdings',70341,245472,7)")
    mc.commit()
    cur.execute("insert into BANKING values('Bank Of America',88000,200000,35)")
    mc.commit()
    cur.execute("insert into BANKING values('Credit Agricole SA',74590,73950,10)")
    mc.commit()
    cur.execute("insert into BANKING values('Visa',118000,21500,205)")
    mc.commit()
    cur.execute("insert into BANKING values('Mastercard',108000,24000,336)")
    mc.commit()
    cur.execute("insert into BANKING values('BNP Paribas',110000,190000,50)")
    mc.commit()
    cur.execute("insert into BANKING values('HSBC',80000,232957,7)")
    mc.commit()
    cur.execute("insert into BANKING values('Wells Fargo',86000,268351,45)")
    mc.commit()
    cur.execute("insert into BANKING values('Morgan Stanley',94000,17646,89)")
    mc.commit()
    cur.execute("create table CONSULTANCY(company varchar(50), wage int(50), employee int(50), stock int(50))")
    mc.commit()
    cur.execute("insert into CONSULTANCY values('PWC',96000,295000,106)")
    mc.commit()
    cur.execute("insert into CONSULTANCY values('Deloitte',100000,345374,85)")
    mc.commit()
    cur.execute("insert into CONSULTANCY values('Ernest and Young',95000,312250,73)")
    mc.commit()
    cur.execute("insert into CONSULTANCY values('KPMG',91000,236000,94)")
    mc.commit()
    cur.execute("insert into CONSULTANCY values('McKinsey',93000,100000,56)")
    mc.commit()
    cur.execute("insert into CONSULTANCY values('Boston consulting group',92000,210000,83)")
    mc.commit()
    cur.execute("insert into CONSULTANCY values('IBM',106000,282100,129)")
    mc.commit()
    cur.execute("insert into CONSULTANCY values('Booz Allen Hamlton',89000,293456,93)")
    mc.commit()
    cur.execute("insert into CONSULTANCY values('Bain and Company',88000,130000,82)")
    mc.commit()
    cur.execute("insert into CONSULTANCY values('Oliver Wyman',98000,70884,97)")
    mc.commit()

def files():
    fo = open("datact.txt","w")
    fo.write ("Welcome to Datact\nInstructions for use:\nWhen prompted, input choice value (number) as per displayed menu\n")
    fo.write ("After entering chosen field, choose option for the data you wish to see.\n")
    fo.write ("Please make sure to input only the item number as per menu, else an error will be found.\n")
    fo.write ("________________________________________________________________________________________\n")
    fo.close()
    fo = open("datact.txt","r")
    l = fo.read()
    print (l)
    
def delete():
    cur.execute("drop table IT ")
    mc.commit()
    cur.execute("drop table MEDICAL")
    mc.commit
    cur.execute("drop table SPORTING")
    mc.commit()
    cur.execute("drop table AUTOMOBILES")
    mc.commit()
    cur.execute("drop table APPAREL")
    mc.commit()
    cur.execute("drop table BANKING")
    mc.commit()
    cur.execute("drop table CONSULTANCY")
    mc.commit()
    
    
def prin():
    while True :
        create()
        print(" Here are the list of fields ")
        print(" 1. IT ")
        print(" 2. MEDICAL ")
        print(" 3. SPORTING ")
        print(" 4. AUTOMOBILES ")
        print(" 5. APPAREL ")
        print(" 6. BANKING ")
        print(" 7. CONSULTANCY\n ")
        
        ch = int(input(" Enter desired field number : "))
        if ch==1:
            nm=['Google', 'Microsoft', 'Apple', 'Oracle', 'Accenture', 'Hewlett-Packard', 'Meta', 'TCS', 'Capgemini', 'Infosys']
            
            print("\nHere are the company statistical data\n ")
            print("1. Median wage ")
            print("2. Number of Employees ")
            print("3. Stock Value ")
            ch2 = int(input(" Enter choice: "))
            if ch2==1:
                cur.execute("select wage from IT")
                w=cur.fetchall()
                p.plot(nm,w)
                p.xlabel("Companies")
                p.ylabel("Wages ($)")
                p.show()
            if ch2==2:
                cur.execute("select employee from IT")
                e=cur.fetchall()
                p.plot(nm,e)
                p.xlabel("Companies")
                p.ylabel(" No. of Employees")
                p.show()
            if ch2==3:
                cur.execute("select stock from IT")
                s=cur.fetchall()
                p.plot(nm,s)
                p.xlabel("Companies")
                p.ylabel("Stock Prices ($)")
                p.show()
            else:
                print("Invalid input")
                
        elif ch==2:
            nm=['Pfizer','Roche','Abbvie','Johnson & Johnson','Novartis','Bayer','Merck','Bristol Myers Squibb','GlaxoSmithKline','Sanofi']
            
            print("\nHere are the company statistical data\n ")
            print("1. Median wage ")
            print("2. Number of Employees ")
            print("3. Stock Values ")
            ch2 = int(input(" Enter choice: "))
            if ch2==1:
                cur.execute("select wage from MEDICAL")
                w=cur.fetchall()
                p.plot(nm,w)
                p.xlabel("Companies")
                p.ylabel("Wages ($)")
                p.show()
            if ch2==2:
                cur.execute("select employee from MEDICAL")
                e=cur.fetchall()
                p.plot(nm,e)
                p.xlabel("Companies")
                p.ylabel(" No. of Employees")
                p.show()
            if ch2==3:
                cur.execute("select stock from MEDICAL")
                s=cur.fetchall()
                p.plot(nm,s)
                p.xlabel("Companies")
                p.ylabel("Stock Prices ($)")
                p.show()
            else:
                print("Invalid input")
            
        elif ch==3:
            nm=['Nike','Academy Sports','Bass Pro Shop','Adidas','Recreational Equipments','Big 5 Sporting Goods','Modells sport goods','Puma','Reebok','Decathlon']
            
            print("\nHere are the company statistical data\n ")
            print("1. Median Wage ")
            print("2. Number of Employees ")
            print("3. Stock Values ")
            ch2 = int(input(" Enter choice: "))
            if ch2==1:
                cur.execute("select wage from SPORTING")
                w=cur.fetchall()
                p.plot(nm,w)
                p.xlabel("Companies")
                p.ylabel("Wages ($)")
                p.show()
            if ch2==2:
                cur.execute("select employee from SPORTING")
                e=cur.fetchall()
                p.plot(nm,e)
                p.xlabel("Companies")
                p.ylabel(" No. of Employees")
                p.show()
            if ch2==3:
                cur.execute("select stock from SPORTING")
                s=cur.fetchall()
                p.plot(nm,s)
                p.xlabel("Companies")
                p.ylabel("Stock Prices ($)")
                p.show()
            else:
                print("Invalid input")
        
            
        elif ch==4:
            nm=['Toyota','Volkswagen','Daimler','Ford Motor','Honda Motor','Tesla','General Motors','Fiat','Hyundai','Nissan']
            
            print("\nHere are the company statistical data\n ")
            print("1. Median wage ")
            print("2. Number of Employees ")
            print("3. Stock Values ")
            ch2 = int(input(" Enter choice: "))
            if ch2==1:
                cur.execute("select wage from AUTOMOBILES")
                w=cur.fetchall()
                p.plot(nm,w)
                p.xlabel("Companies")
                p.ylabel("Wages ($)")
                p.show()
            if ch2==2:
                cur.execute("select employee from AUTOMOBILES")
                e=cur.fetchall()
                p.plot(nm,e)
                p.xlabel("Companies")
                p.ylabel(" No. of Employees")
                p.show()
            if ch2==3:
                cur.execute("select stock from AUTOMOBILES")
                s=cur.fetchall()
                p.plot(nm,s)
                p.xlabel("Companies")
                p.ylabel("Stock Prices ($)")
                p.show()
            else:
                print("Invalid input")

        
        elif ch==5:
            nm=['Raymonds','Allen Solly','Pantaloons','Alexandaer McQueen','Armani','ASM clothing','Gucci','Prada','Hermes','Burberry']
            print("\nHere are the company statistical data\n")
            print("1. Median Wage ")
            print("2. Number of Employees ")
            print("3. Stock Values ")
            ch2 = int(input("\n Enter choice: "))
            if ch2==1:
                cur.execute("select wage from APPAREL")
                w=cur.fetchall()
                p.plot(nm,w)
                p.xlabel("Companies")
                p.ylabel("Wages ($)")
                p.show()
            if ch2==2:
                cur.execute("select employee from APPAREL")
                e=cur.fetchall()
                p.plot(nm,e)
                p.xlabel("Companies")
                p.ylabel(" No. of Employees")
                p.show()
            if ch2==3:
                cur.execute("select stock from APPAREL")
                s=cur.fetchall()
                p.plot(nm,s)
                p.xlabel("Companies")
                p.ylabel("Stock Prices ($)")
                p.show()
            else:
                print("Invalid input")
        elif ch==6:
            nm=['JP Morgan','Japan Post Holdings','Bank of America','Credit Agricole SA','Visa','Mastercard','BNP Paribas','HSBC','Wells Fargo','Morgan Stanley']
            
            print("\nHere are the company statistical data\n")
            print("1. Median Wage ")
            print("2. Number of Employees ")
            print("3. Stock Values ")
            ch2 = int(input("\nEnter choice: "))
            if ch2==1:
                cur.execute("select wage from BANKING")
                w=cur.fetchall()
                p.plot(nm,w)
                p.xlabel("Companies")
                p.ylabel("Wages ($)")
                p.show()
            if ch2==2:
                cur.execute("select employee from BANKING")
                e=cur.fetchall()
                p.plot(nm,e)
                p.xlabel("Companies")
                p.ylabel(" No. of Employees")
                p.show()
            if ch2==3:
                cur.execute("select stock from BANKING")
                s=cur.fetchall()
                p.plot(nm,s)
                p.xlabel("Companies")
                p.ylabel("Stock Prices ($)")
                p.show()
            else:
                print("Invalid input")
            
        elif ch==7:
            nm=['PWC','Deloitte','Ernest Young','KPMG','McKinsey','Boston','IBM','Booz Allen Hamlton','Bain and Company','Oliver Wyman']
            
            print("Here are the company statistical data ")
            print("1. Median wage ")
            print("2. Number of employees ")
            print("3. stock value ")
            ch2 = int(input("Enter choice: "))
            if ch2==1:
                cur.execute("select wage from CONSULTANCY")
                w=cur.fetchall()
                p.plot(nm,w)
                p.xlabel("Companies")
                p.ylabel("Wages ($)")
                p.show()
            if ch2==2:
                cur.execute("select employee from CONSULTANCY")
                e=cur.fetchall()
                p.plot(nm,e)
                p.xlabel("Companies")
                p.ylabel(" No. of Employees")
                p.show()
            if ch2==3:
                cur.execute("select stock from CONSULTANCY")
                s=cur.fetchall()
                p.plot(nm,s)
                p.xlabel("Companies")
                p.ylabel("Stock Prices ($)")
                p.show()
            else:
                print("Invalid input")
        else:
            print("Invalid input")
        for i in cur:
            print(i)
       
        ch = input("Do you wish to continue? (y/n): ")
        if ch in 'yY':
            delete()
        else:
            delete()
            break
files()
prin()

    
    
